CREATE TABLE SD_USER_DETAILS (
  USER_ID VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(50) NOT NULL,
  PIN_CODE VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (USER_ID, PIN_CODE)
);

CREATE TABLE SD_PRODUCT_DETAILS (
  PRODUCT_ID VARCHAR(50) NOT NULL,
  PRODUCT_NAME VARCHAR(50) NOT NULL,
  PRODUCT_HEIGHT VARCHAR(50) NOT NULL,
  PRODUCT_WIDTH VARCHAR(50) NOT NULL,
  PRODUCT_DEPTH VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE SD_PIN_CODE (
  PIN_CODE VARCHAR(50) NOT NULL,
  LOCKER_ID VARCHAR(50) NOT NULL,
  LOCKER_LOCATION VARCHAR(255) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (LOCKER_ID)
);

CREATE TABLE SD_LOCKER_SHELF_DETAILS (
  SHELF_ID VARCHAR(50) NOT NULL,
  SHELF_SIZE VARCHAR(50) NOT NULL,
  SHELF_STATUS VARCHAR(50) NOT NULL DEFAULT 'EMPTY',
  LOCKER_ID VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (SHELF_ID)
);

CREATE TABLE SD_COURIER_DRIVERS (
  DRIVER_ID VARCHAR(50) NOT NULL,
  PIN_CODE VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (PIN_CODE)
);

CREATE SEQUENCE SD_DELIVERY_DETAILS_SEQ START WITH 1 MINVALUE 1 MAXVALUE 999999999999999999 NOCYCLE;

CREATE TABLE SD_DELIVERY_DETAILS (
  ORDER_ID INT(11) NOT NULL DEFAULT NEXTVAL(SD_DELIVERY_DETAILS_SEQ),
  PRODUCT_ID VARCHAR(50) NOT NULL,
  LOCKER_ID VARCHAR(50) NOT NULL,
  PIN_CODE VARCHAR(50) NOT NULL,
  SHELF_ID VARCHAR(50) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL,
  PASSCODE VARCHAR(50) NOT NULL,
  ORDERE_STATUS VARCHAR(50) NOT NULL,
  DRIVER_ID VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UPDATED_DATE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (PRODUCT_ID, LOCKER_ID)
);
